export enum RouteTo {
  Home = '/',
  Login = '/login',
  Signup = '/signup',
  SignupComplete = '/signup-complete',
  Onboarding = '/onboarding',
  LevelTest = '/leveltest',
  LevelTestResult = '/testresult',

  Solve = '/solve',
  Mypage = '/mypage',
  Rank = '/rank',
  SolveRandom = '/solve/random',
  Announcement = '/announcement',
  Suggestion = '/suggestion',
  WriteSuggestion = '/suggestion/write',
  Store = '/store',
  StorePurchaseHistory = '/store/purchase-history',

  AdminLogin = '/admin',
  AdminDashboard = '/admin/dashboard',
  AdminManagementUser = '/admin/management/user',
  AdminManagementProblem = '/admin/management/problem',
  AdminManagementProblemDetail = '/admin/management/problem/detail',
  AdminManagementProblemUpdate = '/admin/management/problem/update',
  AdminManagementProblemCreate = '/admin/management/problem/create',
  AdminManagementProblemDelete = '/admin/management/problem/delete',
}
