import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/feature/header/ui/Header';
import { Provider } from '@/components/ui/provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="h-screen w-screen">
      <body
        id="root-container"
        className={`flex h-full w-full font-spoqa antialiased`}
      >
        <Provider>
          <div className="base h-full w-full">
            <div className="fixed z-[100] flex h-[3rem] w-full md:h-[3.5rem]">
              <Header />
            </div>
            <div className="mt-[3rem] flex h-[calc(100%-3rem)] w-full justify-center bg-pointcolor-yogurt md:mt-[3.5rem] md:h-[calc(100%-3.5rem)]">
              {children}
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
