/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 스터디 메이트 API 문서 (Dev)
 * 스터디메이트 BFF Server API 문서 (Dev)
 * OpenAPI spec version: v1
 */

export type BoardDtoStatus =
  (typeof BoardDtoStatus)[keyof typeof BoardDtoStatus];

export const BoardDtoStatus = {
  RECEIVED: 'RECEIVED',
  IN_REVIEW: 'IN_REVIEW',
  REJECTED: 'REJECTED',
  ACCEPTED: 'ACCEPTED',
} as const;
