/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 스터디 메이트 API 문서 (Dev)
 * 스터디메이트 BFF Server API 문서 (Dev)
 * OpenAPI spec version: v1
 */
import type { GetUserDto } from './getUserDto';
import type { BoardDtoCategory } from './boardDtoCategory';
import type { BoardDtoStatus } from './boardDtoStatus';
import type { CommentDto } from './commentDto';

export interface BoardDto {
  id?: number;
  user?: GetUserDto;
  title?: string;
  content?: string;
  category?: BoardDtoCategory;
  status?: BoardDtoStatus;
  view?: number;
  comments?: CommentDto[];
  createdDt?: string;
}
