/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 스터디 메이트 API 문서 (Dev)
 * 스터디메이트 BFF Server API 문서 (Dev)
 * OpenAPI spec version: v1
 */

export type CategoryDetailDtoCategoryOriginName =
  (typeof CategoryDetailDtoCategoryOriginName)[keyof typeof CategoryDetailDtoCategoryOriginName];

export const CategoryDetailDtoCategoryOriginName = {
  ALGORITHUM_MAQ: 'ALGORITHUM_MAQ',
  ALGORITHUM_SAQ: 'ALGORITHUM_SAQ',
  OS_MAQ: 'OS_MAQ',
  OS_SAQ: 'OS_SAQ',
  NETWORK_MAQ: 'NETWORK_MAQ',
  NETWORK_SAQ: 'NETWORK_SAQ',
  DB_MAQ: 'DB_MAQ',
  DB_SAQ: 'DB_SAQ',
  LEVEL_TEST: 'LEVEL_TEST',
} as const;
