/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 스터디 메이트 API 문서 (Dev)
 * 스터디메이트 BFF Server API 문서 (Dev)
 * OpenAPI spec version: v1
 */
import type { CreateSaqQuestionRequestDtoCategory } from './createSaqQuestionRequestDtoCategory';

export interface CreateSaqQuestionRequestDto {
  questionTitle: string;
  questionContent: string;
  answer: string;
  answerExplanation: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  difficulty?: number;
  category?: CreateSaqQuestionRequestDtoCategory;
  keyword1: string;
  keyword2: string;
  keyword3: string;
}
