/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 스터디 메이트 API 문서 (Dev)
 * 스터디메이트 BFF Server API 문서 (Dev)
 * OpenAPI spec version: v1
 */
import type { GetQuestionDetailResponseDtoCategory } from './getQuestionDetailResponseDtoCategory';

export interface GetQuestionDetailResponseDto {
  questionId?: string;
  questionTitle?: string;
  content?: string;
  difficulty?: number;
  options?: string;
  category?: GetQuestionDetailResponseDtoCategory;
  answer?: string;
  answerExplanation?: string;
}
