/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 스터디 메이트 API 문서 (Dev)
 * 스터디메이트 BFF Server API 문서 (Dev)
 * OpenAPI spec version: v1
 */

export type GetUserDtoLoginType =
  (typeof GetUserDtoLoginType)[keyof typeof GetUserDtoLoginType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserDtoLoginType = {
  LOCAL: 'LOCAL',
  GITHUB: 'GITHUB',
  KAKAO: 'KAKAO',
  NAVER: 'NAVER',
  GOOGLE: 'GOOGLE',
} as const;
