/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 스터디 메이트 API 문서 (Dev)
 * 스터디메이트 BFF Server API 문서 (Dev)
 * OpenAPI spec version: v1
 */
import type { MaqQuestionDtoCategory } from './maqQuestionDtoCategory';

export interface MaqQuestionDto {
  id?: string;
  questionTitle?: string;
  content?: string;
  difficulty?: number;
  category?: MaqQuestionDtoCategory;
  choice1?: string;
  choice2?: string;
  choice3?: string;
  choice4?: string;
}
