/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 스터디 메이트 API 문서 (Dev)
 * 스터디메이트 BFF Server API 문서 (Dev)
 * OpenAPI spec version: v1
 */
import type { NoticeDtoNoticeCategory } from './noticeDtoNoticeCategory';

export interface NoticeDto {
  noticeId?: number;
  noticeTitle?: string;
  noticeContent?: string;
  noticeCategory?: NoticeDtoNoticeCategory;
  noticePurpose?: string;
  pulbisherName?: string;
  backgroundImage?: string;
  displayStartTime?: string;
  displayEndTime?: string;
  maintenanceStartTime?: string;
  maintenanceEndTime?: string;
}
