/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 스터디 메이트 API 문서 (Dev)
 * 스터디메이트 BFF Server API 문서 (Dev)
 * OpenAPI spec version: v1
 */
import type { QuestionDetailDtoQuestionCategory } from './questionDetailDtoQuestionCategory';

export interface QuestionDetailDto {
  questionId?: string;
  questionTitle?: string;
  questionContent?: string;
  questionCategory?: QuestionDetailDtoQuestionCategory;
  questionAnswer?: string;
  questionExplanation?: string;
  difficulty?: number;
  createdDt?: string;
}
