/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 스터디 메이트 API 문서 (Dev)
 * 스터디메이트 BFF Server API 문서 (Dev)
 * OpenAPI spec version: v1
 */
import type { SolveStatsDto } from './solveStatsDto';

export interface SolveStatsResponseDto {
  solveStats?: SolveStatsDto[];
  startDate?: string;
  endDate?: string;
}
