name: Deploy to Vercel
on:
  push:
    branches:
      - stg

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env
          echo "NEXT_PUBLIC_GITHUB_AUTH_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GITHUB_AUTH_CLIENT_ID }}" >> .env
          echo "NEXT_PUBLIC_GITHUB_AUTH_CLIENT_SECERT=${{ secrets.NEXT_PUBLIC_GITHUB_AUTH_CLIENT_SECERT }}" >> .env
          echo "NEXT_PUBLIC_GITHUB_REDIRECT_URI=${{ secrets.NEXT_PUBLIC_GITHUB_REDIRECT_URI }}" >> .env
          echo "NEXT_PUBLIC_GOOGLE_AUTH_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_AUTH_CLIENT_ID }}" >> .env
          echo "NEXT_PUBLIC_GOOGLE_AUTH_REDIRECT_URI=${{ secrets.NEXT_PUBLIC_GOOGLE_AUTH_REDIRECT_URI }}" >> .env
          echo "NEXT_PUBLIC_GOOGLE_AUTH_SCOPE=${{ secrets.NEXT_PUBLIC_GOOGLE_AUTH_SCOPE }}" >> .env
          echo "NEXT_PUBLIC_VAPID_PUBLIC_KEY=${{ secrets.NEXT_PUBLIC_VAPID_PUBLIC_KEY }}" >> .env
          echo "VAPID_PRIVATE_KEY=${{ secrets.VAPID_PRIVATE_KEY }}" >> .env

      - name: Build project
        run: pnpm build

      - name: Install Vercel CLI
        run: pnpm add -g vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --yes --prod --token=${{ secrets.VERCEL_TOKEN }}
